// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import shared

/**
 * selector: ClassContext/Sample202209:util/sobaya/app/util/Result */
public enum ResultKs<T : AnyObject> {

  case error(ResultError)
  case loading
  case success(ResultSuccess<T>)

  public var sealed: ResultKt {
    switch self {
    case .error(let obj):
      return obj as! ResultKt
    case .loading:
      return ResultLoading() as! ResultKt
    case .success(let obj):
      return obj as! ResultKt
    }
  }

  public init(_ obj: ResultKt) {
    if let obj = obj as? ResultError {
      self = .error(obj)
    } else if obj is ResultLoading {
      self = .loading
    } else if let obj = obj as? ResultSuccess<T> {
      self = .success(obj)
    } else {
      fatalError("ResultKs not synchronized with Result class")
    }
  }

}
