// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import shared

/**
 * selector: ClassContext/Sample202209:util/sobaya/app/util/Result */
public enum ResultKs<T : AnyObject> {

  case error(FlowResultError)
  case loading
  case success(FlowResultSuccess<T>)

  public var sealed: FlowResult {
    switch self {
    case .error(let obj):
      return obj as! FlowResult
    case .loading:
      return FlowResultLoading() as! FlowResult
    case .success(let obj):
      return obj as! FlowResult
    }
  }

  public init(_ obj: FlowResult) {
    if let obj = obj as? FlowResultError {
      self = .error(obj)
    } else if obj is FlowResultLoading {
      self = .loading
    } else if let obj = obj as? FlowResultSuccess<T> {
      self = .success(obj)
    } else {
      fatalError("ResultKs not synchronized with Result class")
    }
  }

}
