// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import shared

/**
 * selector: ClassContext/Sample202209:util/sobaya/app/util/Result */
public enum ResultKs<T : AnyObject> {

  case error(UtilResultError)
  case loading
  case success(UtilResultSuccess<T>)

  public var sealed: UtilResult {
    switch self {
    case .error(let obj):
      return obj as! UtilResult
    case .loading:
      return UtilResultLoading() as UtilResult
    case .success(let obj):
      return obj as! UtilResult
    }
  }

  public init(_ obj: UtilResult) {
    if let obj = obj as? UtilResultError {
      self = .error(obj)
    } else if obj is UtilResultLoading {
      self = .loading
    } else if let obj = obj as? UtilResultSuccess<T> {
      self = .success(obj)
    } else {
      fatalError("ResultKs not synchronized with Result class")
    }
  }

}
